#!/usr/bin/env bash

# This script is designed to run in terminal environments similar to s4vitar's setup.
SUDO_PASSWORD="SET_YOUR_PSSWRD" # <--- Important

if [ "$EUID" -ne 0 ]; then
	echo -e "\033[1;31m[!] You need to be root to perform this action. ;)\033[0m"
    exit 1
fi

clear

printf "\033c"

echo -e "\n      \033[1;37m		⛧ Ultimate Terminal Automation on bspwm | BY: YiKyu | https://github.com/Yi-Kyu ⛧\033[0m\n"

valid_ip() {
    local ip=$1
    local IFS=.
    read -r i1 i2 i3 i4 <<< "$ip"

    [[ "$ip" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]] || return 1

    for octet in $i1 $i2 $i3 $i4; do
        ((octet >= 0 && octet <= 255)) || return 1
    done

    return 0
}

auto_tab() {
    local name="$1"
    xdotool key ctrl+shift+t
    sleep 0.3
    xdotool key ctrl+shift+alt+t
    sleep 0.3
    for i in {1..6}; do
        xdotool key alt+BackSpace
        sleep 0.05
    done
xdotool type "$MACHINE - $MACHINE_IP - $MACHINE_OS"
xdotool key Return

}

move_left_tab() {
    xdotool key ctrl+shift+Left
    sleep 0.3
}

echo -e "\n[*] Which machine are we working on today? ;)"
read -e -p "Enter name: " MACHINE

while true; do
    read -e -p "Enter the machine IP: " MACHINE_IP
    if valid_ip "$MACHINE_IP"; then
        break
    else
        echo "[-] No, no, no, this IP is not valid. Try again >:)"
    fi
done

read -e -p "Is it Linux or Windows? " MACHINE_OS

MACHINE_DIR="$PENTEST_DIR/$MACHINE"

BASE_PATH="/SET/YOUR/PATH/HERE" # <--- Important
MACHINE_DIR="$BASE_PATH/$MACHINE"

if [ ! -d "$MACHINE_DIR" ]; then
    echo -e "\n[+] Creating machine directory: $MACHINE_DIR"
    mkdir -p "$MACHINE_DIR" || { echo "[!] Error while creating directory"; exit 1; }

    echo "[+] Running mkt inside the directory as root..."
    sudo zsh -c "cd '$MACHINE_DIR' && source /root/.zshrc && mkt"
else
    echo -e "\n[-] Directory already exists: $MACHINE_DIR"
fi

for i in {1..5}; do
    xdotool key ctrl+shift+t
    sleep 0.2
done

sleep 0.5 

declare -a TABS=("scripts" "exploits" "content" "nmap" "$MACHINE - $MACHINE_IP - $MACHINE_OS")

for name in "${TABS[@]}"; do
    if [[ "$name" == "$MACHINE - $MACHINE_IP - $MACHINE_OS" ]]; then
    xdotool type "cd '$MACHINE_DIR'"
else
    xdotool type "cd '$MACHINE_DIR/$name'"
fi

    xdotool key ctrl+shift+alt+t
    sleep 0.3
    for i in {1..6}; do
        xdotool key alt+BackSpace
        sleep 0.05
    done
    xdotool type "$name"
    xdotool key Return
    sleep 0.2

    move_left_tab
done

xdotool key ctrl+shift+Right
sleep 0.3

for i in {1..5}; do

    xdotool key Return
    sleep 0.2

    xdotool type "sudo su"
    xdotool key Return
    sleep 0.3

    xdotool type "$SUDO_PASSWORD"
    xdotool key Return
    sleep 0.5

    xdotool key ctrl+shift+Right
    sleep 0.3
done

echo "[*] Closing original tab in 1.3 seconds..."
sleep 1.3
xdotool key ctrl+shift+w

notify-send "Pentest Environment Ready" "Everything is ready for the machine: $MACHINE ($MACHINE_IP - $MACHINE_OS)" --urgency=normal --icon=utilities-terminal
